"""
MindMirror AI - Optimized Main Application

High-performance version using TensorFlow with GPU acceleration for Mac M2.
Fallback to educational implementation if TensorFlow is not available.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

import argparse
import time

# Import the optimized AI (which has built-in fallback)
from core.ai import MindMirrorAI

def load_training_data(file_path: str = None) -> str:
    """Load training data from file or use default"""
    if file_path and os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        print(f"📁 Loaded {len(content)} characters from {file_path}")
        return content
    else:
        # Enhanced default training data for better learning
        return """
Hello! I am MindMirror, your personal AI assistant built from scratch using neural networks.
I can learn patterns in text and generate responses based on what I've learned.

I understand that learning is a gradual process, much like how humans learn.
The more text I see, the better I become at understanding and generating language.
Neural networks are fascinating because they can learn complex patterns from simple examples.

Each neuron in my network processes information and passes it to other neurons.
Through backpropagation, I adjust my weights to minimize errors and improve my responses.
I am constantly learning and evolving, just like biological neural networks.

Artificial intelligence is not magic - it's mathematics, statistics, and lots of practice.
The key to my intelligence is the ability to find patterns in data and use them to make predictions.
Every conversation teaches me something new about language and communication.

I process text by converting characters into numbers, then using neural networks to understand patterns.
My training involves adjusting millions of parameters to minimize prediction errors.
The beauty of neural networks is their ability to learn representations automatically.

I hope we can have many interesting conversations as I continue to learn and grow!
Thank you for building me from scratch - it means I truly understand my own architecture.
Machine learning is a journey of continuous improvement and discovery.

My responses are generated by predicting the most likely next characters given the context.
Temperature controls how creative or conservative my responses are.
I can learn from any text you provide, adapting to different styles and topics.

Neural networks work by passing information through layers of interconnected nodes.
Each connection has a weight that gets adjusted during training.
The forward pass computes predictions, while the backward pass updates weights.

I represent one possible approach to building AI from first principles.
By understanding how I work, you gain insight into the nature of artificial intelligence.
The future of AI lies in combining human understanding with machine learning capabilities.
"""


def train_ai(ai: MindMirrorAI, data_file: str = None, epochs: int = 100):
    """Train the AI on text data with progress tracking"""
    print("🤖 Starting AI Training...")
    print(f"🔧 Implementation: {'TensorFlow (optimized)' if hasattr(ai, 'using_tensorflow') and ai.using_tensorflow else 'Educational (from scratch)'}")
    
    # Load training data
    training_text = load_training_data(data_file)
    print(f"📚 Loaded {len(training_text)} characters of training data")
    
    # Prepare training data
    print("⚙️  Preparing training data...")
    ai.learn_from_text(training_text)
    
    # Train the AI with timing
    print(f"🎯 Training for {epochs} epochs...")
    start_time = time.time()
    
    ai.train(epochs=epochs, learning_rate=0.01)
    
    end_time = time.time()
    training_time = end_time - start_time
    print(f"✅ Training completed in {training_time:.2f} seconds!")
    print(f"⚡ Average time per epoch: {training_time/epochs:.3f} seconds")
    
    return ai


def interactive_mode(ai: MindMirrorAI):
    """Run interactive chat mode with enhanced commands"""
    print("\n🎯 MindMirror AI - Interactive Mode")
    print("Type 'quit' to exit, 'help' for commands")
    print("=" * 50)
    
    # Set initial temperature for generation
    temperature = 0.7
    
    while True:
        try:
            user_input = input("\n👤 You: ").strip()
            
            if user_input.lower() in ['quit', 'exit', 'q']:
                print("👋 Goodbye!")
                break
            elif user_input.lower() == 'help':
                print("\n📋 Available Commands:")
                print("  help - Show this help")
                print("  generate <length> - Generate text (e.g., 'generate 100')")
                print("  temp <value> - Set temperature 0.1-2.0 (e.g., 'temp 0.8')")
                print("  info - Show AI information")
                print("  stats - Show generation statistics")
                print("  quit - Exit")
                continue
            elif user_input.lower().startswith('generate'):
                parts = user_input.split()
                length = int(parts[1]) if len(parts) > 1 and parts[1].isdigit() else 100
                print(f"🎲 Generating {length} characters...")
                start_time = time.time()
                response = ai.generate(max_length=length, temperature=temperature)
                gen_time = time.time() - start_time
                print(f"🤖 Generated ({gen_time:.2f}s): {response}")
                continue
            elif user_input.lower().startswith('temp'):
                parts = user_input.split()
                if len(parts) > 1:
                    try:
                        new_temp = float(parts[1])
                        if 0.1 <= new_temp <= 2.0:
                            temperature = new_temp
                            print(f"🌡️  Temperature set to {temperature}")
                        else:
                            print("❌ Temperature must be between 0.1 and 2.0")
                    except ValueError:
                        print("❌ Invalid temperature value")
                else:
                    print(f"🌡️  Current temperature: {temperature}")
                continue
            elif user_input.lower() == 'info':
                print(f"\n🤖 AI Information:")
                print(f"   Implementation: {'TensorFlow (optimized)' if hasattr(ai, 'using_tensorflow') and ai.using_tensorflow else 'Educational (from scratch)'}")
                print(f"   Context Length: {getattr(ai, 'context_length', 'Unknown')}")
                print(f"   Hidden Size: {getattr(ai, 'hidden_size', 'Unknown')}")
                print(f"   Vocabulary Size: {getattr(ai, 'vocab_size', 'Unknown')}")
                print(f"   Temperature: {temperature}")
                continue
            elif user_input.lower() == 'stats':
                print("📊 Generation statistics not implemented yet")
                continue
            elif not user_input:
                continue
            
            # Generate response to user input
            print("🤔 Thinking...")
            start_time = time.time()
            response = ai.chat_response(user_input)
            response_time = time.time() - start_time
            print(f"🤖 MindMirror ({response_time:.2f}s): {response}")
            
        except KeyboardInterrupt:
            print("\n👋 Goodbye!")
            break
        except Exception as e:
            print(f"❌ Error: {e}")
            import traceback
            traceback.print_exc()


def demo_mode(ai: MindMirrorAI):
    """Run demonstration mode with enhanced examples"""
    print("\n🎭 MindMirror AI - Demo Mode")
    print("=" * 50)
    
    # Show AI information
    print(f"🤖 AI Implementation: {'TensorFlow (optimized)' if hasattr(ai, 'using_tensorflow') and ai.using_tensorflow else 'Educational (from scratch)'}")
    
    # Show some generated text
    print("\n📝 Text Generation Examples:")
    print("   (Each example shows different generation behaviors)")
    
    prompts = [
        ("Hello", "Simple greeting"),
        ("I am", "Self-description"),
        ("Neural networks", "Technical explanation"),
        ("Learning is", "Educational concept"),
        ("", "Free generation")
    ]
    
    for prompt, description in prompts:
        print(f"\n🎲 {description} - Prompt: '{prompt}'")
        try:
            start_time = time.time()
            generated = ai.generate(prompt=prompt, max_length=80, temperature=0.7)
            gen_time = time.time() - start_time
            print(f"   → {generated} ({gen_time:.2f}s)")
        except Exception as e:
            print(f"   ❌ Error: {e}")
    
    # Show learning capabilities
    print(f"\n🧠 Learning Capabilities:")
    print(f"   Context Length: {getattr(ai, 'context_length', 'Unknown')}")
    print(f"   Vocabulary Size: {getattr(ai, 'vocab_size', 'Unknown')}")
    print(f"   Hidden Layer Size: {getattr(ai, 'hidden_size', 'Unknown')}")


def benchmark_mode(ai: MindMirrorAI):
    """Run performance benchmarks"""
    print("\n⚡ Performance Benchmark Mode")
    print("=" * 50)
    
    # Test generation speed
    print("🚀 Testing generation speed...")
    test_lengths = [50, 100, 200]
    
    for length in test_lengths:
        print(f"\n📏 Generating {length} characters:")
        times = []
        for i in range(3):  # 3 runs for average
            start_time = time.time()
            ai.generate(max_length=length, temperature=0.7)
            times.append(time.time() - start_time)
        
        avg_time = sum(times) / len(times)
        chars_per_sec = length / avg_time
        print(f"   Average time: {avg_time:.3f}s ({chars_per_sec:.1f} chars/sec)")
    
    print(f"\n🎯 Implementation: {'TensorFlow (GPU-accelerated)' if hasattr(ai, 'using_tensorflow') and ai.using_tensorflow else 'Educational (CPU-only)'}")


def main():
    """Main application entry point with enhanced features"""
    parser = argparse.ArgumentParser(description="MindMirror AI - Personal AI Assistant")
    parser.add_argument("--mode", choices=["train", "chat", "demo", "benchmark"], default="demo",
                        help="Run mode: train, chat, demo, or benchmark")
    parser.add_argument("--data", type=str, help="Training data file path")
    parser.add_argument("--epochs", type=int, default=50, help="Training epochs (default: 50)")
    parser.add_argument("--context", type=int, default=8, help="Context length (default: 8)")
    parser.add_argument("--hidden", type=int, default=64, help="Hidden layer size (default: 64)")
    parser.add_argument("--learning-rate", type=float, default=0.01, help="Learning rate (default: 0.01)")
    parser.add_argument("--no-train", action="store_true", help="Skip training (use pre-trained weights)")
    
    args = parser.parse_args()
    
    print("🌟 Welcome to MindMirror AI!")
    print("Your personal AI assistant built from scratch")
    print("=" * 50)
    
    # Show system information
    try:
        import tensorflow as tf
        gpus = tf.config.experimental.list_physical_devices('GPU')
        print(f"🖥️  System: {len(gpus)} GPU(s) detected" if gpus else "🖥️  System: CPU-only mode")
    except:
        print("🖥️  System: CPU-only mode (TensorFlow not available)")
    
    # Initialize AI with specified parameters
    print(f"⚙️  Initializing AI (context: {args.context}, hidden: {args.hidden})...")
    ai = MindMirrorAI(context_length=args.context, hidden_size=args.hidden)
    
    if args.mode == "train":
        train_ai(ai, args.data, args.epochs)
    elif args.mode == "chat":
        if not args.no_train:
            train_ai(ai, args.data, args.epochs)
        interactive_mode(ai)
    elif args.mode == "demo":
        if not args.no_train:
            train_ai(ai, args.data, args.epochs)
        demo_mode(ai)
        
        # Ask if user wants to continue
        print("\n" + "=" * 50)
        response = input("🤔 What would you like to do next?\n   (c)hat, (b)enchmark, or (q)uit: ").strip().lower()
        if response in ['c', 'chat']:
            interactive_mode(ai)
        elif response in ['b', 'bench', 'benchmark']:
            benchmark_mode(ai)
        elif response in ['q', 'quit']:
            print("👋 Goodbye!")
        else:
            print("👋 Goodbye!")
    elif args.mode == "benchmark":
        if not args.no_train:
            train_ai(ai, args.data, args.epochs)
        benchmark_mode(ai)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n👋 Goodbye!")
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
